name:                Hit
version:             0.1.0.0
github:              "bakala12/Hit"
license:             BSD3
author:              "Mateusz Bąkała"
maintainer:          "bakala12@github.com"
copyright:           "2018 Mateusz Bąkała"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/Hit#readme>

dependencies:
- base >= 4.7 && < 5
- directory #directory operations, file permissions
- bytestring
- cryptohash #SHA1
- transformers
- zlib #object serialization
- parsec
- time #timestamp
- MissingH #string utils
- strict #strict IO
- filepath
- containers
- stringbuilder
- Diff

library:
  source-dirs: src

executables:
  Hit:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hit

tests:
  Hit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Hit
